# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kRUsrxckE6fiLnudGtEMaRDWQuKnSQSD
"""

mon=int(input("введите номер месяца:"))
if mon==1:
  print("Январь")
elif  mon==2:
  print("Февраль")
elif  mon==3:
  print("Март")
elif  mon==4:
  print("Апрель")
elif  mon==5:
  print("Май")
elif  mon==6:
  print("Июнь")
elif  mon==7:
  print("Июль")
elif  mon==8:
  print("Август")
elif  mon==9:
  print("Сентябрь")
elif  mon==10:
  print("Октябрь")
elif  mon==11:
  print("Ноябрь")
elif  mon==12:
  print("Декабрь")
else:    
  print("ошибка")

x=int(input("введите число:"))
if x%2==1:
  print("число нечётное")
else:
  print("число чётное")

N=int(input())
if N>40:
  print("stonks")
elif N<40:
  print("not stonks")
else:
  print("экономическая неопределённость")

y=int(input())
def is_year_leap(y):
  if y%4==0:
    return True
  else:
    return False
is_year_leap(y)

import re
n=int(input("введите искомое число:"))
def is_prime(n):
  if n>9 and (n%2==0 or n%3==0 or n%4==0 or n%5==0 or n%6==0 or n%7==0 or n%8==0 or n%9==0 or n%10==0):
    return False 
  elif n==1 or n==2 or n==3 or n==5 or n==7:
    return True
  elif n==4 or n==6 or n==8 or n==9:
    return False
  else:
    return True
is_prime(abs(n))

from math import fabs
a = int(input())
b = int(input())
print (a,b)
if a / b > 3.6 or b > ((-138/2)**1.3 - 1) and b < (fabs(((-69/28**5.1)*4) + 1)):
  a,b = b,a
print (a,b)

a = int(input())
b = int(input())
c = int(input())
d = int(input())
f = int(input())
t = 0
p = 0
j = 0
numbers = (a,b,c,d,f)
print (set(numbers), "список чисел")
for i in numbers:
  if i % 2 == 0:
    t += 1
  if i < 0:
    p += 1
  if i > -257 and i < 1025:
    j += 1
result = (t,p,j)
print(t, "чётных чисед",p , " отрицательных числе", j, " числе в интервале[-256 ; 1024]включительно.")
print(set(result),"итог")

a = int(input())
b = int(input())
c = int(input())
n = ((a ** 2 + b ** 3) / c + 3) / 4
if n % 2 == 0:
  print ("четное")
else:
  print ("нечетное")